name: client_zipcare
description: ZipCare App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  google_fonts: ^4.0.3
  otp_text_field: ^1.1.3
  flutter_riverpod: ^2.2.0
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  intl: ^0.17.0
  country_picker: ^2.0.19
  flutter_chat_ui: ^1.6.6
  file_picker: ^5.2.5
  flutter_credit_card: 3.0.5
  image_picker: ^0.8.6+1
  mime: ^1.0.4
  uuid: ^3.0.7
  http: ^0.13.5
  path_provider: ^2.0.12
  open_filex: ^4.3.2
  video_player: ^2.5.2
  data_table_2: ^2.3.12
  flutter_rating_bar: ^4.0.1
  flick_video_player: ^0.5.0
  percent_indicator: ^4.2.2
  dropdown_button2: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/messages.json
    - assets/images/
    - assets/images/intro/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
